### ISSUE TITLE
NaxRiscv gets the wrong value when reading from `scause`

### ISSUE THREAD

**Issue by zhangkanqi** [SpinalHDL/NaxRiscv#100]
**Environment:**
commit id: 6af1a20158f6402196c1f17f47680b96e0a88b86

**Description:**
The instructions are as follows: (from spike.log)
<img src="https://github.com/SpinalHDL/NaxRiscv/assets/34207592/65b5c111-f2c6-4175-aeaa-2e5978625614" width="75%">
(1) Set `scause`  to 0xc0010;
(2) Then encounters an illegal_instruction exception;
(3) Read `scause` and get value 0xc0010;

NaxRiscv does the same as Spike in step (1) and (2). However,  **NaxRiscv gets 0x0 in step (3) while Spike gets the expected value 0xc0010**.

**For debug and reproduce:**
[input_6.zip](https://github.com/SpinalHDL/NaxRiscv/files/15413465/input_6.zip)
```
./obj_dir/VNaxRiscv --load-elf=./input_nax_6.elf --start-symbol=_start --pass-symbol=write_tohost --timeout=99999 --name=input_nax_6 --trace --trace-ref --spike-debug
```

I have no idea why NaxRiscv gets 0x0 when reading `scause`. Could you help me solve this problem?

**Comment by Dolu1990** [comment]
Hi,

scause is implemented with bits XLEN-1 and 3:0
All the other bits are hard wired to 0.

Which is a valid implementation, scause shouldn't be used to store arbitrary value.

**Comment by Dolu1990** [comment]
I meant that only a few bits of mcause/scause are implemented. Those bits can be read write by both the hardware and the software
