### ISSUE TITLE
NaxRiscv sets sepc[0]=1 which is against the riscv privileged spec

### ISSUE THREAD

**Issue by zhangkanqi** [SpinalHDL/NaxRiscv#101]
Hi, 
when I run instruction `csrrwi  a1, sepc, 21`, I found an mismatch between Spike and NaxRiscv.

In detail, the value of `sepc` after executing csrrwi is `0x15` in NaxRiscv, while it is `0x14` in Spike.

According to the riscv privileged spec, `sepc[0]` should always be **zero**. It seems that NaxRiscv violates this rule.
<img src="https://github.com/SpinalHDL/NaxRiscv/assets/34207592/ee891fd9-88e7-4e84-a23d-dae5db158d85" width="70%">

**Comment by Dolu1990** [comment]
Hi,

Right, i fix need to be made :)
