### ISSUE TITLE
Question about the sizes of cache L2 & L1

### ISSUE THREAD

**Issue by phillippZZ** [SpinalHDL/NaxRiscv#109]
Hi, Dolu. 
I succeeded to simulate naxriscv with 4 cpu cores by using litex under your guidance. But later on I noticed that the size of cache L2 doesn't seem to be bigger than L1(I suppose "sram:8kb" represents the size of cache L1).
Could you tell me if I forgot to specify something? Just as a reminder, I used "litex/litex/tools/litex_sim.py --cpu-type=naxriscv --with-sdram --sdram-data-width=64 --sdram-init images/boot.json --cpu-count=4" to simulate.
![MicrosoftTeams-image](https://github.com/SpinalHDL/NaxRiscv/assets/171099706/72a174f0-a10f-4130-a26f-4bdf92ef098d)
![MicrosoftTeams-image (1)](https://github.com/SpinalHDL/NaxRiscv/assets/171099706/7630cb11-daa1-48bd-a9de-d786df04a921)

**Comment by Dolu1990** [comment]
Hi,

That's ok, that L2 cache is internal to litex and NaxRiscv will not read memory through it. Nax coherent infrastructure has its own l2 coherent cache which is 128 KB by default normaly.

Idealy, i would need to have it disabled automaticaly for Nax/Vexii cpus targets in litex.

**Comment by phillippZZ** [comment]
Oh, I see. So the "l2" option in this case is actually related the wishbone stuff. I'll disable it. Thank you very much.

**Comment by Dolu1990** [comment]
Hi ^^
Always 64 bytes

**Comment by phillippZZ** [comment]
Got it! I'll remember it in my heart : )

**Comment by phillippZZ** [comment]
Hi, @Dolu1990. Thank you for the help all the time. 
I've finished several tests on the naxriscv and everything goes well. 
But I do have one question and maybe few more in the future about the cache 😅
Given that l2 has total size as 128kb, cache line size as 64 kb and 8 ways by default, can I say that the number of sets are 256 by default? Do we decide the total size, line size and number of ways of l2 cache first, and then the number of sets can be calculated naturally?

**Comment by Dolu1990** [comment]
> sets are 256 by default?

256 is correct

> Do we set the total size, line size and number of ways of l2 cache first,  and then the number of sets can be calculated automatically?

yes right

> L1 L2 

L1 are 4 way 64 sets
L2 is 8 way 256 sets
