### ISSUE TITLE
Performance counter CSR registers that are not implemented are seen as implemented

### ISSUE THREAD

**Issue by Bill94l** [SpinalHDL/NaxRiscv#121]
Hi,

The attached code tries to read a `mhpmcounter23h` that is not implemented, on the spike side it throws an exception, but on the DUT side it commits because the register is seen as implemented. With the knowledge that this register is only available in 32 bits, I launched the code in NaxRiscv 64 bits.

[basic_test_0_csrrci.zip](https://github.com/user-attachments/files/16440569/basic_test_0_csrrci.zip)

**Execution Result**
```
[info] *** DUT missed a trap ***
[info] commit error
[info] - std::exception
```

**Spike.log**
```
core   0: 0x0000000080000160 (0x00001817) auipc   a6, 0x1
core   0: 3 0x0000000080000160 (0x00001817) x16 0x0000000080001160
core   0: 0x0000000080000164 (0xa7880813) addi    a6, a6, -1416
core   0: 3 0x0000000080000164 (0xa7880813) x16 0x0000000080000bd8
core   0: 0x0000000080000168 (0xb970fbf3) csrrci  s7, mhpmcounter23h, 1
core   0: exception trap_illegal_instruction, epc 0x0000000080000168
core   0:           tval 0x00000000b970fbf3
```

**Tracer.log**
```
rv rf w 0 0 32 0000000080001160
rv commit 0 0000000080000160
rv rf w 0 0 32 0000000080000bd8
rv commit 0 0000000080000164
rv rf w 0 0 32 0000000000000000
rv rf r 0 4 2967 0000000000000000
rv rf w 0 4 2967 0000000000000000
rv commit 0 0000000080000168
```
https://github.com/SpinalHDL/NaxRiscv/blob/5211920b9f945963135419126087c998828f7d07/src/main/scala/naxriscv/misc/PerformanceCounterPlugin.scala#L49-L55

In this part of the code you filter the CSRs that are needed according to XLEN and the privilege which gives us the csrFilter list which contains the implemented registers

https://github.com/SpinalHDL/NaxRiscv/blob/5211920b9f945963135419126087c998828f7d07/src/main/scala/naxriscv/misc/PerformanceCounterPlugin.scala#L58

In this line you include all the performance CSR registers that exist in the RISCV specification, which can be decoded.

https://github.com/SpinalHDL/NaxRiscv/blob/5211920b9f945963135419126087c998828f7d07/src/main/scala/naxriscv/execute/CsrAccessPlugin.scala#L160-L165

- The decode list includes all the registers in the specification, but should we only include the list of implemented registers? Any suggestions on how to fix this? 

- How to synchronise Spike with the DUT on the number of performance counters implemented ?

At the moment, if we are trying to access a performance csr register that is present in the RISCV specification but not implemented on NaxRiscv, we do not have a trap.

**Comment by Dolu1990** [comment]
Thanks ^^
Should be fixed with the above commit.

**Comment by Dolu1990** [comment]
> How to synchronise Spike with the DUT on the number of performance counters implemented ?

In general what i do, is that i configure NaxRiscv to have as much counters than Spike.
But more generaly, it should be when the user ask RVLS to create a new CPU isntance, more parameters should be given to specify this kind of implementation specific caracteristics.

**Comment by Bill94l** [comment]
Hi,

The attached riscv-dv generated code attempts to access mhpmcounter10, which is not implemented in either the DUT or Spike. This results in a segmentation fault and the code fails. Below is the specific line of code causing the issue:
```asm
    800001b6:	b0aa15f3          	csrrw	a1,mhpmcounter10,s4
```

Knowing that I have modified the number of HPM counters in Spike to ensure consistency between the DUT and Spike but that doesn't change anything: 
https://github.com/SpinalHDL/riscv-isa-sim/blob/5b37ab699f6176ea7f2d2b3187f75625eca7e511/riscv/processor.h#L22
```c
#define N_HPMCOUNTERS 7 //29
```

### Results:
1. **With the regression simulator:**
  ```log
  ./obj_dir/VNaxRiscv --name dv --output-dir failed --load-elf basic_test_1.o --start-symbol _start --pass-symbol pass --fail-symbol fail --no-putc-flush --seed 96102624 ${ARGS} --trace-ref
  
  *** MISSMATCH PC DUT=80103000 REF=8010301c ***
  
  TIME=574
  LAST PC COMMIT=80103000
  INCOMING SPIKE PC=80101bf8
  ROB_ID=x1c
  FAILURE dv
  ```

2. **With RVLS using SocSim**
  ```log
  [info] **************************************************
  [info] DUT-PC = 00000000800001b6, REF-PC=800001b6, INST = b0aa15f3
  [info] Debug: CSR_MHPMCOUNTER3 = 0xb03, CSR_MHPMCOUNTER31 = 0xb1f, csrAddress = 0xb0a, csrReadData = 0x0
  [info] Warning: csrmap[0xb0a] is null. Skipping write.
  [info] # A fatal error has been detected by the Java Runtime Environment:
  [info] #
  [info] #  SIGSEGV (0xb) at pc=0x00007ffa1f6e01e8, pid=2445164, tid=0x00007ffa68e47640
  [info] #
  [info] # JRE version: OpenJDK Runtime Environment (8.0_432) (build 1.8.0_432-8u432-ga~us1-0ubuntu2~22.04-ga)
  [info] # Java VM: OpenJDK 64-Bit Server VM (25.432-bga mixed mode linux-amd64 compressed oops)
  [info] # Problematic frame:
  [info] # C  [rvls.so+0x3a91e8]  processor_t::get_csr(int, insn_t, bool, bool)+0x58
  [info] #
  [info] # Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
  [info] #
  [info] # An error report file with more information is saved as:
  [info] # /media/big_dd/nanotrust/bi262934/naxriscv_tuleap/naxriscv_dv_vf/NaxRiscv/hs_err_pid2445164.log
  [info] #
  [info] # If you would like to submit a bug report, please visit:
  [info] #   http://bugreport.java.com/bugreport/crash.jsp
  [error] Nonzero exit code returned from runner: 134
  [error] (Compile / runMain) Nonzero exit code returned from runner: 134
  [error] Total time: 12 s, completed 10 déc. 2024 00:09:08
  ```

[failed_test.zip](https://github.com/user-attachments/files/18069407/failed_test.zip)

Could you please provide guidance on how to handle this mismatch or segmentation fault when accessing unimplemented HPM counters? 

Thank you!
