### ISSUE TITLE
About performance evaluation

### ISSUE THREAD

**Issue by yyyjjp** [SpinalHDL/NaxRiscv#124]
Hi！
I've seen some performance evaluation programs like coremark and dhrystone, and the final results are really good.
But these evaluation programs may be too small? Is it better to use the SPEC CPU 2006 or 2017 suite to perform performance evaluation work with Naxriscv?

**Comment by Dolu1990** [comment]
> But these evaluation programs may be too small?

Yes right. They test nothing about the memory system.

>  Is it better to use the SPEC CPU 2006 or 2017 suite to perform performance evaluation work with Naxriscv?

Yes, very likely, but i do not have access to those, as they aren't free of usage for open-source stuff. I do not have a license.
It would also be interresting to test on [VexiiRiscv](https://github.com/SpinalHDL/VexiiRiscv) 

More generaly, there isn't many open-source benchmark out there :/
