### ISSUE TITLE
64-bit version NaxRiscv linux support

### ISSUE THREAD

**Issue by YiminGao0113** [SpinalHDL/NaxRiscv#23]
Hi,

I wanted to ask if the 64-bit NaxRiscv can run Linux. I followed the steps to run Linux with naxriscv rv32ima and it works well, but ran into issues (failures) when I switched to a 64-bit core. 
Could you please give me some pointers to run Linux using 64-bit core? Thanks!

![image](https://user-images.githubusercontent.com/79269558/223909473-d66a52c9-be9d-4a6a-aa76-39c4733771a9.png)

**Comment by Dolu1990** [comment]
Hi,

Should have worked. Can you check : 

```shell
NaxRiscv $ ls ext/NaxSoftware/buildroot/images/rv64ima
fw_dynamic.bin  fw_dynamic.elf  fw_jump.bin  fw_jump.elf  Image  linux.dtb  rootfs.cpio  vmlinux
```

?

Thanks ^^

**Comment by YiminGao0113** [comment]
Hi,
It seems the same on my end: 
![image](https://user-images.githubusercontent.com/79269558/223930930-1d5a8102-2c01-48ac-ab0b-2aea628247a1.png)
Thanks.

**Comment by Dolu1990** [comment]
seems like you had the $NAXRISCV path not set.
Should be set to the absolute path to the NaxRiscv  :)

**Comment by Dolu1990** [comment]
seems like you had the $NAXRISCV path not set.
Should be set to the absolute path to the NaxRiscv  :)

**Comment by YiminGao0113** [comment]
Thanks for your reply! 
But I had set up the $NAXRISCV in terminal when I installed and set up everything, this is a new tab in the terminal
I just added it to my .bashrc file, but still facing the same issue. :0
![image](https://user-images.githubusercontent.com/79269558/223937312-cde469da-7958-4b98-8f4b-960f99366b47.png)

**Comment by Dolu1990** [comment]
Ahh , you need to regenerate the CPU in 64 bits mode, and regenerate the simulator

**Comment by YiminGao0113** [comment]
Got it! 
However, (this could be a silly question) but I haven't found any instructions for configuring the core in 64bits. Which file do I need to change to generate 64-bit? 
Thanks!

**Comment by Dolu1990** [comment]
sbt “runMain naxriscv.Gen64” :)

**Comment by YiminGao0113** [comment]
Got it! It is working now, thank you very much for your help!
