### ISSUE TITLE
Are there any plans to add TAGE Branch Predictor in the future?

### ISSUE THREAD

**Issue by ghost** [SpinalHDL/NaxRiscv#30]
Are there plans to add TAGE Branch Predictor as a plugin in the future?

**Comment by Dolu1990** [comment]
Hi, currently there is no plan for it, but it would be a great thing to have.
Not sure how well it would fit in a FPGA, would probably need a 2 cycle latency prediction instead of the current 1 cycle latency (to get good timings)
