### ISSUE TITLE
The FSM in PrivilegedPlugin

### ISSUE THREAD

**Issue by xie-1399** [SpinalHDL/NaxRiscv#33]
Hi !
I See a very complex statemachine in the PrivilegedPlugin,the code is between 720 and 966 lines，Can you show me a picture about how the statemachine works? Thank you very mush :)
![9d14228e9b5b720deb052c0614505f3](https://github.com/SpinalHDL/NaxRiscv/assets/62367053/201119fb-ad7b-4c08-ac1e-b40c9f4597b3)

**Comment by Dolu1990** [comment]
Hi ^^

So, that FSM will handle all exception / interrupt / debug context switches. 
It will also handle re-scheduling service which can be used to failed instruction CAUSE_REDO (ex memory load after memory write hazard) .
And another service to allow rescheduling all the instruction after the current one (which commited successfuly), allowing for instance to reschedule the code which follow a sfence.vma (as the MMU status changed and we want it to be effective for all following instruction).

One thing a bit specific in NaxRiscv, is that "many" CSR states are stored in a unified LUT-RAM to save area. So for instance, the MTVEC / MEPC / ... are stored in the same LUT-RAM.
That FSM will take a few cycles to read / update that LUT-RAM to execute the context switch.

That's mostly it :)
