### ISSUE TITLE
Interactive debug of the simulated CPU via GDB OpenOCD and Verilator

### ISSUE THREAD

**Issue by ghost** [SpinalHDL/NaxRiscv#42]
Hi ^^
I'm trying to run the debug module of NaxRiscv using GDB OpenOCD and Verilator, as mentioned in VexRiscv. But I don't have any ideas.  Following the debug process of Vexriscv, I found that the problems were VNaxRiscv being unable to run, openod missing yaml files, and gdb missing uart files. How can I debug in Naxriscv? Could you give me some suggestions?

**Comment by Dolu1990** [comment]
Hi,
So using the same openocd fork than for VexRiscv, you can do : 
src/openocd -f ../NaxRiscv/src/main/tcl/openocd/naxriscv_sim.tcl

That should be good then ^^

**Comment by ElianZh** [comment]
I have some trouble:
When i run the simulation VNaxRiscv: `./obj_dir/VNaxRiscv`
it can't boot like VVexRiscv, and it shows:
`DUT is blocked in a endless trap cycle of death
TIME=434
LAST PC COMMIT=0
INCOMING SPIKE PC=0
ROB_ID=x0
FAILURE ???`
And Openocd can't connect to the TCP server.
How should i solve these problems? Thank you!

**Comment by Dolu1990** [comment]
Hooo right, when you connect with the TCP thing, you need first to disable the lockstep checking done in the testbench
--spike-disabled --timeout-disabled

**Comment by ElianZh** [comment]
Success！
Thanks for your reply!  :)
