### ISSUE TITLE
settings64.sh

### ISSUE THREAD

**Issue by HimalSubedi787** [SpinalHDL/NaxRiscv#46]
I tried 

python3 -m litex_boards.targets.digilent_nexys_video --cpu-type=naxriscv --with-video-framebuffer --with-sdcard --build --load

but i get this error 

OSError: Unable to find or source Vivado toolchain, please either:
- Source Vivado's settings manually.
- Or set LITEX_ENV_VIVADO environment variant to Vivado's settings path.
- Or add Vivado toolchain to your $PATH.

 Do you know how to solve this issue with finding or sourcing the Vivado toolchain for my  project.

**Comment by Dolu1990** [comment]
You need to set LITEX_ENV_VIVADO environment variant to Vivado's settings path. 

For instance :
export LITEX_ENV_VIVADO=/?/?/Vivado/2023.1
