### ISSUE TITLE
L1 data caches are inclusive in the L2 cache? 

### ISSUE THREAD

**Issue by SoCScholar** [SpinalHDL/NaxRiscv#50]
Is L1 data caches are inclusive in the L2 cache ?

 

//TODO L1 status tracking into L2 need to be exact, so need to notify when going from shared to invalid/another line.
https://github.com/SpinalHDL/NaxRiscv/blob/main/src/main/scala/naxriscv/lsu/DataCache.scala#L695

i am wondering if it is in to do list ? 

is cache in multicore non coherent ? 

https://github.com/SpinalHDL/NaxRiscv/blob/main/src/main/scala/naxriscv/platform/litex/NaxSoc.scala#L89 

nonCoherent = cache.down
    
what does it mean ?

**Comment by Dolu1990** [comment]
Hi,

L2 is inclusive with L1 D$.

> When we switch the SoC will the memory layout be different ?

What do you mean by switch ?

> //TODO L1 status tracking into L2 need to be exact, so need to notify when going from shared to invalid/another line.

Outdated todo, it is implemented already.

> is cache in multicore non coherent ?

Caches in multicore are coherent

> nonCoherent = cache.down

nonCoherent variable is used to point to the tilelink buse from which no more memory coherency is handled anymore, it became just a regular read/write bus.

**Comment by Dolu1990** [comment]
> Can you give me idea how is L2 is inclusive with L1 D$. ? 

So mostly done here : 
https://github.com/SpinalHDL/SpinalHDL/blob/dev/lib/src/main/scala/spinal/lib/bus/tilelink/coherent/Cache.scala#L991

When there is a aquire from a CPU but the l2 miss, it will alway allocate a line.

Also, when a cache line in the l2 is replaced and the replaced line is owned by some L1, a probe is automaticaly sent to all those l1 to flush them : 
https://github.com/SpinalHDL/SpinalHDL/blob/dev/lib/src/main/scala/spinal/lib/bus/tilelink/coherent/Cache.scala#L845

> Moreover, I am also curious how Caches in multi-core are coherent ?

I added some documentation here : 
https://spinalhdl.github.io/NaxRiscv-Rtd/main/NaxRiscv/memory/index.html#coherency

Basicaly, l1 caches need to acquire permitions from the l2 to do operations on a given memory block.
