### ISSUE TITLE
\= should only assign combinatorial signals

### ISSUE THREAD

**Issue by ronan-lashermes** [SpinalHDL/NaxRiscv#53]
Related to latest SpinalHDL update.
Two such errors in naxriscv.utilities.AllocatorMultiPort lines 63 and 92.
I have no clue how to solve them.

**Comment by Dolu1990** [comment]
Hi, 
Right, should be fixed with https://github.com/SpinalHDL/NaxRiscv/commit/e2c46ef1bcdf11e1a102479a0a2c9b0056fc2852

**Comment by ronan-lashermes** [comment]
Working ! Thanks
