### ISSUE TITLE
How to use SocDemo.elf file ?

### ISSUE THREAD

**Issue by SoCScholar** [SpinalHDL/NaxRiscv#60]
Hi,

i found one issues with 

naxRiscv/ext/NaxSoftware/baremetal/socdemo/src

is there any problem with **la load address**? it throws below errors 

```
make compile OBJDIR=build/rv32ima  MARCH=rv32ima MABI=ilp32

CC src/crt.S

src/crt.S: Assembler messages:

src/crt.S:14: Error: illegal operands `la x1,(0x14000000+0*0x80)+0x10'
src/crt.S:27: Error: illegal operands `la x1,(0x14000000+0*0x80)+0x10'
src/crt.S:32: Error: illegal operands `la x1,(0x10000000+0x8)'
src/crt.S:34: Error: illegal operands `la x1,0x10000000'
src/crt.S:39: Error: illegal operands `la x1,(0x14000000+0xF04)'
src/crt.S:41: Error: illegal operands `la x1,(0x14000000+0xF24)'
src/crt.S:44: Error: illegal operands `la x1,(0x10000000+0x8)'
src/crt.S:46: Error: illegal operands `la x1,0x10000000'

make[1]: *** [../common/asm.mk:88: build/rv32ima//home/hsubedi/instruction_test_bed/riscv_NAX_2_l2_cache_new_pull
/NaxRiscv4_gtkwave/naxRiscv/ext/NaxSoftware/baremetal/socdemo/src/crt.o] Error 1

make: *** [../common/asm.mk:104: rv32ima] Error 2

```

How to use **socdemo.elf**  generate file that is produce after make rv32ima ? is gtkwave is right one to use along with using sbt server?

is there any command line to use ?

```
like below command

runMain naxriscv.platform.tilelinkdemo.SocSim --load-elf play.elf --load-elf socdemo.elf --trace --nax-count 2 --no-rvls

```

Thank you so much

**Comment by Dolu1990** [comment]
socdemo.elf : 

```
cd NaxRiscv/ext/NaxSoftware/baremetal/socdemo/
make rv32ima
```

Works fine for me.

You can only load one elf. the second one will just override the first one.

**Comment by Dolu1990** [comment]
On my side, i did a 
runMain naxriscv.platform.tilelinkdemo.SocSim --load-elf ext/NaxSoftware/baremetal/socdemo/build/rv32ima/socdemo.elf

And got 
```
[info] [Progress] Verilator compilation done in 1854.314 ms
[info] [Progress] Start SocDemo test simulation with seed 2
[info] Sim starting <3
[info] 00000004
[info] 00000007
[info] i$ refill = 6
[info] d$ refill = 4
[info] [Done] Simulation done in 73.549 m
```

You dont ?

**Comment by Dolu1990** [comment]
Solved by https://github.com/SpinalHDL/NaxRiscv/issues/58#issuecomment-1794986232

**Comment by Dolu1990** [comment]
Seems like the code you are executing is reading the address 0 ?
Can you give me your play.asm ?

**Comment by Dolu1990** [comment]
ahh yes, i meant socdemo.elf

So looking at your rv32ima.zip, i realy don't understand how you have this kind of sequaneces in the asm : 

8000004c:	0000a503          	lw	a0,0(ra) # 10000000 <_start-0x70000000>
80000050:	00a0a023          	sw	a0,0(ra)

Did you modified the assembly code ?
How did you compiled it ?

**Comment by Dolu1990** [comment]
Ahh what GCC version do you have ?

me
riscv64-unknown-elf-gcc --version
riscv64-unknown-elf-gcc () 11.1.0

**Comment by Dolu1990** [comment]
lw x10, 0(x1) // This is the issue, why did you added it ?
 sw x10, 0(x1)

**Comment by Dolu1990** [comment]
pushed
