### ISSUE TITLE
LINUX on Litex_NaxRISCV  ( Linux-capable, RISC-V-based SoC ) 

### ISSUE THREAD

**Issue by SoCScholar** [SpinalHDL/NaxRiscv#86]
Hi charles, 

How will it be possible to run linux on Litex-Naxriscv like as  https://github.com/litex-hub/linux-on-litex-vexriscv

I like to run (NaxRISCV 64 bit ) RISCV 64 Debian Linux on FPGA using Litex.

Thank you so much.

**Comment by Dolu1990** [comment]
Here is some images i did had localy, not sure how good they are : 
https://drive.google.com/drive/folders/1dCTfbEv-6sD5hCpVzpG3LJQC0xOYc3RE?usp=drive_link

Note that is single code dts, and you need to check if the peripherals you have match the same address

**Comment by Dolu1990** [comment]
Not that if you already god a functional opensbi you don't need to take the one i sent

**Comment by Dolu1990** [comment]
[rv32_2c_full_dma_sbi.dts.zip](https://github.com/SpinalHDL/NaxRiscv/files/14551212/rv32_2c_full_dma_sbi.dts.zip)
Here is an example of a 2 core dts, it is about the CPU definition, and the binding to the PLIC, that's all

**Comment by Dolu1990** [comment]
> is it for 64 bits? I am confused as if it is for 32 bits.

Bad file name

Your issue seems that the main memory defined in the dts doesn't match your hardware

**Comment by Dolu1990** [comment]
Hi,

> but it didnot work

Did you checked that the address mapping is right ? (f0002000)
Did you checked that the interrupts mapping is right ? ( = <0x03>;)
Did you checked the dmesg command for ethernet related error ?

Litex can change the address of things at elaboration time, depending what you configured.

> https://github.com/SpinalHDL/NaxRiscv/blob/main/src/test/cpp/naxriscv/README.md#run-linux

This testbench is single core only.

**Comment by Dolu1990** [comment]
i mean, check that the SoC generation you got from litex had the same f0002000 address for ethernet
reg = <0xf0002000 0x7c 0xf0002800 0x0a 0x80000000 0x2000>;

Also, which linux kernel did you used ? (maybe it wasn't complied with the litex ethernet driver)

**Comment by Dolu1990** [comment]
> Ethernet part is working for now

What was broken ?
