### ISSUE TITLE
cache_throttling && dirty evicts counting. 

### ISSUE THREAD

**Issue by SoCScholar** [SpinalHDL/NaxRiscv#87]
Hi charles,

  

I was try to measure L2 cache WB counter for that i change the following but my counter gives me **22 times more** than your counter **L2 WB gives.** while in FPGA prototyping. 
 
Your L2_WB: 
 
```
add((l2c.io.down.a.fire.pull() && l2c.io.down.a.isLast() && l2c.io.down.a.opcode.pull() === spinal.lib.bus.tilelink.Opcode.A.PUT_FULL_DATA), 0xF30)
 
```

can you please have a look where is mistakes why it gives 22 times more counter value by my way of measuring the counter ?? 

You had use the **isLast()** signal that **you use for L2 WB** give accurate counter but for our case i am wondering how my counter can give accurate **L2 WB count value.** 

its on **NaXSoc.scala** 
```
    val scope = new ScopeFiber() {
      up at 0xF1000000l of peripheral.bus  // F1 0000 00 
       
      lock.retain()

      val filler = Fiber build new Area {
        if (withL2) {

          add(l2c.events.evict.clean, 0xF28) // NEWLY ADDED:   test global  
          add(l2c.events.evict.dirty, 0xF2c) // NEWLY ADDED:     test global  L2 WB 

          l2c.rework {
	    add((l2c.io.down.a.fire.pull() && l2c.io.down.a.isLast() && l2c.io.down.a.opcode.pull() === spinal.lib.bus.tilelink.Opcode.A.PUT_FULL_DATA), 0xF30)
	  }

............}
```

F28 and F2c is my dirty clean and **dirty evict counter** which is equal to **L2 WB counter.** 

for that i change in **cache.scala** as below in line around **180-187**  in **cache_throttle branch**  

```
  val events = new Area{
    val getPut = new Area{
      val hit, miss = False
    }
    val acquire = new Area{    // NEWLY ADDED 
      val hit, miss = False        // NEWLY ADDED 
    }                                        // NEWLY ADDED  
    
   val evict = new Area{
      val clean, dirty = False
    }
  
    
  }


```

 Here in line 907 of **cache.scala** in **cache_throttle branch** 

  ```        
        events.evict.dirty setWhen (olderWay.tags.dirty)   // NEWLY ADDED 
        events.evict.clean setWhen (!olderWay.tags.dirty)  // NEWLY ADDED
        
        toReadBackend.address   := olderWay.address
        toReadBackend.size      := log2Up(blockSize)
        toReadBackend.wayId  := olderWay.wayId

```

I am curious to understand the cache.scala **state machine design.**  

the way the cache throttling works (by signalling a REDO signal back to the source), the request is applied again and again and again, and is therefore accounted multiple times. As the state machinery is **quite deterministic**, I wonder how could we detect the *first* occurrence of the requests to get a **reliable signal for accounting the write-backs.**

**Comment by Dolu1990** [comment]
Hi,

> my counter gives me 22 times more

I don't get it, your "add((l2c.io.down.a.fire.pull() && l2c.io.down.a.isLast() && l2c.io.down.a.opcode.pull() === spinal.lib.bus.tilelink.Opcode.A.PUT_FULL_DATA), 0xF30)"
is the same as my "add((l2c.io.down.a.fire.pull() && l2c.io.down.a.isLast() && l2c.io.down.a.opcode.pull() === spinal.lib.bus.tilelink.Opcode.A.PUT_FULL_DATA), 0xF30)"

what are you mesuring exactly ?

**Comment by Dolu1990** [comment]
Ahhhh got it

So the reason why is that my writeback mesurments check L2 writeback to main memory, while your method mesure L1 writeback to L2

**Comment by Dolu1990** [comment]
instead of val dirty = False   in the cache design you can do 
val dirty = io.down.a.fire && io.down.a.isLast() && io.down.a.opcode

**Comment by Dolu1990** [comment]
val dirty = io.down.a.fire && io.down.a.isLast() && io.down.a.opcod === spinal.lib.bus.tilelink.Opcode.A.PUT_FULL_DATA

> Can you please advise the appropriate way how to incorporate the core number that initiated the downstream request so that we can later use it for comparison in generating an event counter ?

That would be tricky.
I'm realy busy / underwater those weeks :/
