### ISSUE TITLE
How to run NaxRiscvRgerssion?

### ISSUE THREAD

**Issue by franktaTian** [SpinalHDL/NaxRiscv#9]
It is an interesting project and I am going to study it,the goal is to be able add FPU. I find the src/test/scala/naxriscv/NaxRiscvRegression.scala, Do you use it to run regression test ? How to run it ?

**Comment by Dolu1990** [comment]
Hi :)

Talking of FPU, it is already done, will be merged very soon in main : 
https://github.com/SpinalHDL/NaxRiscv/tree/fpu/src/main/scala/naxriscv/execute/fpu

**Comment by Dolu1990** [comment]
Let's me know if there is part of the doc realy lacking.
So now with the FPU it should be able to run debian.
I guess possible additional feature would be the bitmanip extention, and memory coherency ^^

**Comment by Dolu1990** [comment]
merged
