### ISSUE TITLE
An exception arose when reading instructions from the ELF file

### ISSUE THREAD

**Issue by zhangkanqi** [SpinalHDL/NaxRiscv#99]
**Environment:**
commit id: f335738370e50d5d23614150c3e8c4a85685e43a

**Description:**
Hi,
I built NaxRiscv according to https://github.com/SpinalHDL/NaxRiscv/blob/main/src/test/cpp/naxriscv/README.md.
Then I run an elf ([input_nax_0.zip](https://github.com/SpinalHDL/NaxRiscv/files/15410469/input_nax_0.zip)) on NaxRiscv with the following command:
```bash
cd $NAXRISCV/src/test/cpp/naxriscv
./obj_dir/VNaxRiscv --load-elf=./input_nax_0.elf --start-symbol=_start --pass-symbol=write_tohost --timeout=100000 --name=input_nax_0 --trace --trace-ref
```
However, it reported:
>  DUT is blocked in a endless trap cycle of death
TIME=668
LAST PC COMMIT=80000ac4
INCOMING SPIKE PC=0
ROB_ID=x27
FAILURE input_nax_0

After debugging the waveform, I found that NaxRiscv reported `illegal instruction` exception with tval='0x0297e101'. The Instructions after PC=0x80000ac4 are as follows:
![image](https://github.com/SpinalHDL/NaxRiscv/assets/34207592/15c75f66-8e57-408d-ada8-3517cadfec37)
It seems that NaxRiscv is confusing `bnez` with `auipc`. However, I have no idea how to solve this problem. Could you please offer some help?

**Comment by Dolu1990** [comment]
Hi,

RVC isn't enabled by default, and i can see that 80000ac8 is a compressed instruction.
Either you need to turn on RVC support in Nax, either you need to compile the binary without RVC :)

**Comment by Dolu1990** [comment]
--timeout=1000000 mean that the simulation should fail if longer than the given amount. It isn't an "inactivity" timeout, but a dead line.

**Comment by Dolu1990** [comment]
bigger ^^, or just remove it

**Comment by Dolu1990** [comment]
i mean software source file

**Comment by Dolu1990** [comment]
i mean the source code which generated input_nax.elf

**Comment by Dolu1990** [comment]
Then you need to check the traces generated by the simulation to see what the software is doing and if it is stuck somwere.
Also note that no missmatch against spike was detected (lock-step sim)
